### ISSUE TITLE
Len vs Count

### ISSUE THREAD

**Issue by namper** [Gogora6/car_wash#1]
https://github.com/Gogora6/car_wash/blob/1c0e8f410e69113e4a4bccd9775cdeeb68eb73df/serviceapp/models.py#L57

len რო წერ, მაგ დროს პითონი ითვლის დაბრუნებუნ კოლექციაზე, ჯობია ბაზას დაათვლევინო 

`Employee.objects.filter(company=self.pk).count()`

**Comment by Gogora6** [comment]
კი კი გეთანხმები, შევასწორე.
