### ISSUE TITLE
related_name is incorrect

### ISSUE THREAD

**Issue by namper** [Gogora6/car_wash#3]
https://github.com/Gogora6/car_wash/blob/1c0e8f410e69113e4a4bccd9775cdeeb68eb73df/serviceapp/models.py#L98

related_name ში გიწერია 'car' რაც შეცდომაა ვინაიდან ბევრ მანქანას შეიძლება ჰქონდეს ერთი და იგივე ტაიპი უდა გეწეროს 'cars'

**Comment by Gogora6** [comment]
გასაგებია ჩავასწორე.
