### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by namper** [Gogora6/car_wash#4]
https://github.com/Gogora6/car_wash/blob/1c0e8f410e69113e4a4bccd9775cdeeb68eb73df/serviceapp/models.py#L71

წარმოიდგინე დასაქმებულების ლისტინგი გაქვს და 100 კაცი მუშაობს ერთ კომპანიაში 
100-ივე ადამიანზე ცალ-ცალკე ითვლი ასაკს. 

ორი ვარიანტია ლისტინგისას გამოიყენო აგგრეგაცია ან ანოტაცია .

`age` გახადო @cached_property

**Comment by Gogora6** [comment]
არ ვიცოდი ეს დეკორატორი, ვიფიქრე ჩემით დავწერ ფუნქციასთქო. გადავხედავ ეხლა მადლობაა.
