### ISSUE TITLE
Charfield.title() unnecessary

### ISSUE THREAD

**Issue by namper** [Gogora6/car_wash#5]
https://github.com/Gogora6/car_wash/blob/1c0e8f410e69113e4a4bccd9775cdeeb68eb73df/serviceapp/models.py#L12
.title არაა საჭირო
`return f'{self.address}, {self.city}' `

**Comment by Gogora6** [comment]
იდეაში აქ მინდოდა ლამაზად ყოფილიყო რა ადმინ პანელში. Title-ს გამოყენებაზე ვფიქრობდი ან capitalize.
