### ISSUE TITLE
WHY ? 

### ISSUE THREAD

**Issue by namper** [Gogora6/car_wash#6]
https://github.com/Gogora6/car_wash/blob/1c0e8f410e69113e4a4bccd9775cdeeb68eb73df/serviceapp/models.py#L41

**Comment by Gogora6** [comment]
იმიტომ გავაკეთე, როგორც მახსოვს მონაცემთა ბაზებში table-ს სახელების შეთანხმება/რჩევა არის ქვედატირებით გამოყოფა.

**Comment by namper** [comment]
ოქეი
